In [1]:
#NUMPY BASICS REVISION

In [2]:
import numpy as np

In [6]:
l = [1,2,3,4,5,6]

arr = np.array(l)

In [7]:
#reshape

arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
#arange between limits and step

a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [13]:
#linspace

b = np.linspace(1,10,5)
b

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
l3 = [11,12,13,14,15]

arr1 = np.array([l1,l2,l3])
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [17]:
#Indexing in multidimensional array

In [20]:
arr1[1:2,3:]

array([[ 9, 10]])

In [21]:
#to get 14,15

In [22]:
arr1[2:,3:]

array([[14, 15]])

In [25]:
#unit matrix

np.ones(6).reshape(2,3)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
#array operations

arr1*arr1

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [29]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [30]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [31]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [35]:
np.zeros((4))

array([0., 0., 0., 0.])

In [36]:
#eye
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
#Random value generation

np.random.randn(3,2)

array([[-0.73910936,  0.79162484],
       [-1.69792325,  1.7959188 ],
       [-0.6800587 ,  1.14397367]])

In [49]:
np.random.randint(1,100,10).reshape(2,5)

array([[82, 34,  5, 91, 80],
       [29, 49, 57, 23, 56]])